# how many recommendations to give
recommendation_size: 3

contexts:
- At Work
- During Commute
- Study Sessions
- During Breaks
- Before Bed
- During Travel

suggestions:
- Mindful Deep Breathing
- Take a Mindful Quick Walk
- Engage in Mindful Music Listening
- Practice Mindful Stretching
- Engage in a Mindful Mini Meditation
- Give Yourself a Mindful Hug with a Pillow
- Engage in Mindful Counting of Your Blessings
- Mindfully Savor a Snack
- Take a Mindful Stroll Down Memory Lane
- Enjoy a Mindful Beverage

# Be sure to make the img_file_name as <suggestion.png> format:
sugg_dict:
  Mindful Deep Breathing:
    description: Take slow, deep breaths. Inhale for a count of 4, hold for 4, exhale for 4. Repeat a few times.
    img_file_name: Mindful Deep Breathing.png
  Take a Mindful Quick Walk:
    description: Step outside for a short walk around your surroundings. Breathe in fresh air and observe your surroundings.
    img_file_name: Take a Mindful Quick Walk.png
  Engage in Mindful Music Listening:
    description: Put on a favorite calming song or instrumental music and immerse yourself in the sound.
    img_file_name: Engage in Mindful Music Listening.png
  Practice Mindful Stretching:
    description: Do a few simple stretches to loosen tense muscles, like touching your toes or rolling your shoulders.
    img_file_name: Practice Mindful Stretching.png
  Engage in a Mindful Mini Meditation:
    description: Find a quiet spot, close your eyes, and concentrate on your breath or a peaceful image for a few minutes.
    img_file_name: Engage in a Mindful Mini Meditation.png
  Give Yourself a Mindful Hug with a Pillow:
    description: Hug a pillow tightly for a comforting sensation and to release tension.
    img_file_name: Give Yourself a Mindful Hug with a Pillow.png
  Engage in Mindful Counting of Your Blessings:
    description: List three things that went well today and why.
    img_file_name: Engage in Mindful Counting of Your Blessings.png
  Mindfully Savor a Snack:
    description: Grab a small, delicious snack, you deserve it.
    img_file_name: Mindfully Savor a Snack.png
  Take a Mindful Stroll Down Memory Lane:
    description: Reminisce about positive memories to evoke happy feelings.
    img_file_name: Take a Mindful Stroll Down Memory Lane.png
  Enjoy a Mindful Beverage:
    description: Drink some water or whatever you like.
    img_file_name: Enjoy a Mindful Beverage.png

# for all contexts, this records which suggestions to avoid
avoid_indices:
- [5]
- [1, 4, 5]
- [5]
- [5]
- [1, 7, 9]
- [1, 5]

# folder names for files:
image_folder_name: images
general_data_platform: total_data
general_data_user_hash: total

# modify the non-selected suggestions:
modify_non_selected: false   # this can be set as "true" or "false", turn on or off the feature of modifying the non-selected suggestions rewards
threshold_num: 1000          # if you decide to turn on this feature, feature not enabled until total data points exceed this threshold
auxiliary_rewards: 0.5       # if you decide to turn on this feature, rewards to add to those suggested but not selected suggestions (can be negative depending on use cases)

# clustering feature:
enable_cluster: true             # enable cluster feature on or off
cluster_refresh_threshold: 10    # re-cluster after this number of user selections
cluster_reco_ratio: 0.5          # when making recommendation, ratio for cluster (preference vector)
mab_reco_ratio: 0.5              # when making recommendation, ratio for original mab scores
assign_cluster_num: 5            # for new user, after the user made this number of selections, assign to cluster
recluster_threshold: 30         # only re-clustering using k-mean once total selections exceed this threshold